//========================= ALERT ============================
export const TOGGLE_ALERT = 'TOGGLE_ALERT';
export const CHANGE_ALERT = 'CHANGE_ALERT';
export const TOGGLE_CONFIRMATION = 'TOGGLE_CONFIRMATION';

//========================= SOCKET ============================
export const SOCKET_CONNECT = 'SOCKET_CONNECT';

//============= SEARCH =================
export const SET_SEARCH_SUGGESTIONS = 'SET_SEARCH_SUGGESTIONS';
export const CHANGE_SEARCH_VAL = 'CHANGE_SEARCH_VAL';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const DISPLAY_SEARCH_RESULT = 'DISPLAY_SEARCH_RESULT';

//====================== REACT SELECT =========================
export const SET_REACT_SELECT_CURRENT = 'SET_REACT_SELECT_CURRENT';

//=========================== USERS ===========================
export const SET_USER = 'SET_USER';
export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const SET_USERS = 'SET_USERS';
export const SET_SEARCHED_USERS = 'SET_SEARCHED_USERS';
export const SET_USER_DETAIL = 'SET_USER_DETAIL';
export const SET_USER_DEFAULT = 'SET_USER_DEFAULT';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const SET_USER_VALUE = 'SET_USER_VALUE';
export const SET_USER_RECORD_ENTRY = 'SET_USER_RECORD_ENTRY';
export const SET_USER_RECORD_ENTRY_NEW = 'SET_USER_RECORD_ENTRY_NEW';
export const PASSWORD_CHECKED = 'PASSWORD_CHECKED';

//=========================== ROLES ===========================
export const SET_ROLES = 'SET_ROLES';
export const SET_SEARCHED_ROLES = 'SET_SEARCHED_ROLES';
export const ADD_NEW_ROLE = 'ADD_NEW_ROLE';
export const SET_ROLE_DETAIL = 'SET_ROLE_DETAIL';
export const SET_ROLE_VALUE = 'SET_ROLE_VALUE';
export const SET_ROLE_DEFAULT = 'SET_ROLE_DEFAULT';
export const SET_ROLE_NEW_ROUTE = 'SET_ROLE_NEW_ROUTE';
export const SET_ROLE_REMOVE_ROUTE = 'SET_ROLE_REMOVE_ROUTE';
export const SET_ROLE_NEW_SYSTEM = 'SET_ROLE_NEW_SYSTEM';
export const SET_ROLE_REMOVE_SYSTEM = 'SET_ROLE_REMOVE_SYSTEM';

//=========================== LOGS ===========================
export const SET_LOGS = 'SET_LOGS';
export const DISPLAY_LOGS = 'DISPLAY_LOGS';
export const LOGS_COUNT = 'LOGS_COUNT';
export const ADD_NEW_LOG = 'ADD_NEW_LOG';
export const GET_LOG = 'GET_LOG';
export const LOG_VIEWED = 'LOG_VIEWED';
export const LOG_RESOLVED = 'LOG_RESOLVED';
export const SET_LOG_COMMENT = 'SET_LOG_COMMENT';
export const SET_USER_COMMENT = 'SET_USER_COMMENT';

export const SET_SHEET_DATA = 'SET_SHEET_DATA';
export const UPLOAD_STATUS_UPDATE = 'UPLOAD_STATUS_UPDATE';
export const UPDATE_SHEET_STATUS = 'UPDATE_SHEET_STATUS';
export const SET_SHEET_DATA2 = 'SET_SHEET_DATA2';
export const UPLOAD_STATUS_UPDATE2 = 'UPLOAD_STATUS_UPDATE2';
export const UPDATE_SHEET_STATUS2 = 'UPDATE_SHEET_STATUS2';

//=================== OFFICE ===================
export const SET_OFFICES = 'SET_OFFICES';
export const SET_OFFICE_DETAIL = 'SET_OFFICE_DETAIL';
export const SET_OFFICE_DEFAULT = 'SET_OFFICE_DEFAULT';
export const SET_SEARCHED_OFFICES = 'SET_SEARCHED_OFFICES';
export const ADD_NEW_OFFICE = 'ADD_NEW_OFFICE';
export const SET_OFFICE_VALUE = 'SET_OFFICE_VALUE';

//=================== RECORD ===================
export const SET_RECORDS = 'SET_RECORDS';
export const SET_RECORD_DETAIL = 'SET_RECORD_DETAIL';
export const SET_RECORD_DEFAULT = 'SET_RECORD_DEFAULT';
export const SET_SEARCHED_RECORDS = 'SET_SEARCHED_RECORDS';
export const ADD_NEW_RECORD = 'ADD_NEW_RECORD';
export const SET_RECORD_VALUE = 'SET_RECORD_VALUE';
export const SET_RECORD_SUBMITTED = 'SET_RECORD_SUBMITTED';

//-----------------------------------------------
export const SET_REACT_SELECT_RECORD_VALUE   = 'SET_REACT_SELECT_RECORD_VALUE';
export const SET_REACT_SELECT_RECORD_OPTIONS = 'SET_REACT_SELECT_RECORD_OPTIONS';
export const SET_REACT_SELECT_RECORD_CURRENT = 'SET_REACT_SELECT_RECORD_CURRENT';

//=================== RECORD NEW ===================
export const SET_RECORDS_NEW = 'SET_RECORDS_NEW';
export const SET_RECORD_DETAIL_NEW = 'SET_RECORD_DETAIL_NEW';
export const SET_RECORD_DEFAULT_NEW = 'SET_RECORD_DEFAULT_NEW';
export const SET_SEARCHED_RECORDS_NEW = 'SET_SEARCHED_RECORDS_NEW';
export const ADD_NEW_RECORD_NEW = 'ADD_NEW_RECORD_NEW';
export const SET_RECORD_VALUE_NEW = 'SET_RECORD_VALUE_NEW';
export const SET_RECORD_SUBMITTED_NEW = 'SET_RECORD_SUBMITTED_NEW';
export const SET_RECORD_QR_FETCH_DATE = 'SET_RECORD_QR_FETCH_DATE';

export const SET_SELECTED_RECORD_NEW = 'SET_SELECTED_RECORD_NEW';
export const SET_RECORD_NEW_TO_DISPLAY = 'SET_RECORD_NEW_TO_DISPLAY';
export const SET_RECORD_NEW_TO_PRINT_QR = 'SET_RECORD_NEW_TO_PRINT_QR';


//-----------------------------------------------
export const SET_REACT_SELECT_RECORD_VALUE_NEW   = 'SET_REACT_SELECT_RECORD_VALUE_NEW';
export const SET_REACT_SELECT_RECORD_OPTIONS_NEW = 'SET_REACT_SELECT_RECORD_OPTIONS_NEW';
export const SET_REACT_SELECT_RECORD_CURRENT_NEW = 'SET_REACT_SELECT_RECORD_CURRENT_NEW';


//=================== DAHSBOARD ===================
export const SET_DASHBOARD_GRAPHS_DATA = 'SET_DASHBOARD_GRAPHS_DATA';
export const SET_OFFICES_DEVICES_RECORDS_DASHBOARD = 'SET_OFFICES_DEVICES_RECORDS_DASHBOARD';

//=================== DEVICE ===================
export const SET_DEVICES = 'SET_DEVICES';
export const SET_DEVICE_DETAIL = 'SET_DEVICE_DETAIL';
export const SET_DEVICE_DEFAULT = 'SET_DEVICE_DEFAULT';
export const SET_SEARCHED_DEVICES = 'SET_SEARCHED_DEVICES';
export const ADD_NEW_DEVICE = 'ADD_NEW_DEVICE';
export const SET_DEVICE_VALUE = 'SET_DEVICE_VALUE';
export const SET_DEVICE_QR_FETCH_DATE = 'SET_DEVICE_QR_FETCH_DATE';
export const SET_SELECTED_DEVICE = 'SET_SELECTED_DEVICE';
export const SET_DEVICE_TO_DISPLAY = 'SET_DEVICE_TO_DISPLAY';
export const SET_DEVICE_TO_PRINT_QR = 'SET_DEVICE_TO_PRINT_QR';

//=================== USER_COMMENTS ===================
export const SET_USER_COMMENTS = 'SET_USER_COMMENTS';
export const SET_USER_COMMENT_DETAIL = 'SET_USER_COMMENT_DETAIL';
export const SET_USER_COMMENT_DEFAULT = 'SET_USER_COMMENT_DEFAULT';
export const SET_SEARCHED_USER_COMMENTS = 'SET_SEARCHED_USER_COMMENTS';
export const ADD_NEW_USER_COMMENT = 'ADD_NEW_USER_COMMENT';
export const SET_USER_COMMENT_VALUE = 'SET_USER_COMMENT_VALUE';

//=================== JOB_ORDER_REQUEST ===================
export const SET_JOB_ORDER_REQUESTS = 'SET_JOB_ORDER_REQUESTS';
export const SET_JOB_ORDER_REQUEST_DETAIL = 'SET_JOB_ORDER_REQUEST_DETAIL';
export const SET_JOB_ORDER_REQUEST_DEFAULT = 'SET_JOB_ORDER_REQUEST_DEFAULT';
export const SET_SEARCHED_JOB_ORDER_REQUESTS = 'SET_SEARCHED_JOB_ORDER_REQUESTS';
export const ADD_NEW_JOB_ORDER_REQUEST = 'ADD_NEW_JOB_ORDER_REQUEST';
export const SET_JOB_ORDER_REQUEST_VALUE = 'SET_JOB_ORDER_REQUEST_VALUE';
export const SET_JOB_ORDER_ACTION_DEFAULT = 'SET_JOB_ORDER_ACTION_DEFAULT';
export const SET_JOB_ORDER_ACTION_VALUE = 'SET_JOB_ORDER_ACTION_VALUE';
export const SET_JO_REQ_QR_FETCH_DATE = 'SET_JO_REQ_QR_FETCH_DATE';

//=================== APP_MODULE ===================
export const SET_APP_MODULES = 'SET_APP_MODULES';
export const SET_APP_MODULE_DETAIL = 'SET_APP_MODULE_DETAIL';
export const SET_APP_MODULE_DEFAULT = 'SET_APP_MODULE_DEFAULT';
export const SET_SEARCHED_APP_MODULES = 'SET_SEARCHED_APP_MODULES';
export const ADD_NEW_APP_MODULE = 'ADD_NEW_APP_MODULE';
export const SET_APP_MODULE_VALUE = 'SET_APP_MODULE_VALUE';
export const SET_EXCELL_DATA = 'SET_EXCELL_DATA';

//=================== HF_PERSONNEL ===================
export const SET_HF_PERSONNELS = 'SET_HF_PERSONNELS';
export const SET_HF_PERSONNEL_DETAIL = 'SET_HF_PERSONNEL_DETAIL';
export const SET_HF_PERSONNEL_DEFAULT = 'SET_HF_PERSONNEL_DEFAULT';
export const SET_SEARCHED_HF_PERSONNELS = 'SET_SEARCHED_HF_PERSONNELS';
export const ADD_NEW_HF_PERSONNEL = 'ADD_NEW_HF_PERSONNEL';
export const SET_HF_PERSONNEL_VALUE = 'SET_HF_PERSONNEL_VALUE';
export const SET_HF_PERSONNEL_TO_UPLOAD = 'SET_HF_PERSONNEL_TO_UPLOAD';
export const RESET_HF_PERSONNEL_UPLOAD = 'RESET_HF_PERSONNEL_UPLOAD';
export const RESET_HF_PERSONNEL_UPLOAD_BOOL = 'RESET_HF_PERSONNEL_UPLOAD_BOOL';
export const SET_CEIR_DASHBOARD_NUMBERS = 'SET_CEIR_DASHBOARD_NUMBERS';
export const SET_UPLOAD_DETAILS_VALUE = 'SET_UPLOAD_DETAILS_VALUE';
export const SET_PROFESSION_CLASSIFICATION = 'SET_PROFESSION_CLASSIFICATION';
export const SET_CATEGORY_CLASSIFICATION = 'SET_CATEGORY_CLASSIFICATION';
export const SET_HF_PERSONNEL_HEALTH_FACILITIES = 'SET_HF_PERSONNEL_HEALTH_FACILITIES';


export const SET_DOH_CHD_PERSONNELS = 'SET_DOH_CHD_PERSONNELS';
export const SET_DOH_CHD_PERSONNEL_DETAIL = 'SET_DOH_CHD_PERSONNEL_DETAIL';
export const SET_SEARCHED_DOH_CHD_PERSONNELS = 'SET_SEARCHED_DOH_CHD_PERSONNELS';
export const SET_DOH_CHD_PERSONNEL_DEFAULT = 'SET_DOH_CHD_PERSONNEL_DEFAULT';
export const SET_DOH_CHD_SEARCHED_PERSONNELS = 'SET_DOH_CHD_SEARCHED_PERSONNELS';
export const ADD_NEW_DOH_CHD_PERSONNEL = 'ADD_NEW_DOH_CHD_PERSONNEL';
export const SET_DOH_CHD_PERSONNEL_VALUE = 'SET_DOH_CHD_PERSONNEL_VALUE';



//=================== DUPLICATE ===================
export const SET_DUPLICATES = 'SET_DUPLICATES';
export const SET_DUPLICATE_DETAIL = 'SET_DUPLICATE_DETAIL';
export const SET_DUPLICATE_DEFAULT = 'SET_DUPLICATE_DEFAULT';
export const SET_SEARCHED_DUPLICATES = 'SET_SEARCHED_DUPLICATES';
export const ADD_NEW_DUPLICATE = 'ADD_NEW_DUPLICATE';
export const SET_DUPLICATE_VALUE = 'SET_DUPLICATE_VALUE';


//=================== ANNEX_A ===================
export const SET_ANNEX_AS = 'SET_ANNEX_AS';
export const SET_ANNEX_A_DETAIL = 'SET_ANNEX_A_DETAIL';
export const SET_ANNEX_A_DEFAULT = 'SET_ANNEX_A_DEFAULT';
export const SET_SEARCHED_ANNEX_AS = 'SET_SEARCHED_ANNEX_AS';
export const ADD_NEW_ANNEX_A = 'ADD_NEW_ANNEX_A';
export const SET_ANNEX_A_VALUE = 'SET_ANNEX_A_VALUE';


//=================== HEALTH_FACILITY ===================
export const SET_HEALTH_FACILITYS = 'SET_HEALTH_FACILITYS';
export const SET_HEALTH_FACILITY_DETAIL = 'SET_HEALTH_FACILITY_DETAIL';
export const SET_HEALTH_FACILITY_DEFAULT = 'SET_HEALTH_FACILITY_DEFAULT';
export const SET_SEARCHED_HEALTH_FACILITYS = 'SET_SEARCHED_HEALTH_FACILITYS';
export const ADD_NEW_HEALTH_FACILITY = 'ADD_NEW_HEALTH_FACILITY';
export const SET_HEALTH_FACILITY_VALUE = 'SET_HEALTH_FACILITY_VALUE';
export const SET_HF_UPLOAD_DETAILS_VALUE = 'SET_HF_UPLOAD_DETAILS_VALUE';


//=================== VACCINATION_SITES ===================
export const SET_VACCINATION_SITESS = 'SET_VACCINATION_SITESS';
export const SET_VACCINATION_SITES_DETAIL = 'SET_VACCINATION_SITES_DETAIL';
export const SET_VACCINATION_SITES_DEFAULT = 'SET_VACCINATION_SITES_DEFAULT';
export const SET_SEARCHED_VACCINATION_SITESS = 'SET_SEARCHED_VACCINATION_SITESS';
export const ADD_NEW_VACCINATION_SITES = 'ADD_NEW_VACCINATION_SITES';
export const SET_VACCINATION_SITES_VALUE = 'SET_VACCINATION_SITES_VALUE';
export const SET_VACCINATION_TO_UPLOAD_LIST = 'SET_VACCINATION_TO_UPLOAD_LIST';


//=================== PRE_POST_MONITORING ===================
export const SET_PRE_POST_MONITORINGS = 'SET_PRE_POST_MONITORINGS';
export const SET_PRE_POST_MONITORING_DETAIL = 'SET_PRE_POST_MONITORING_DETAIL';
export const SET_PRE_POST_MONITORING_DEFAULT = 'SET_PRE_POST_MONITORING_DEFAULT';
export const SET_SEARCHED_PRE_POST_MONITORINGS = 'SET_SEARCHED_PRE_POST_MONITORINGS';
export const ADD_NEW_PRE_POST_MONITORING = 'ADD_NEW_PRE_POST_MONITORING';
export const SET_PRE_POST_MONITORING_VALUE = 'SET_PRE_POST_MONITORING_VALUE';


//=================== VAS_REPORT ===================
export const SET_VAS_REPORTS = 'SET_VAS_REPORTS';
export const SET_VAS_REPORT_DETAIL = 'SET_VAS_REPORT_DETAIL';
export const SET_VAS_REPORT_DEFAULT = 'SET_VAS_REPORT_DEFAULT';
export const SET_SEARCHED_VAS_REPORTS = 'SET_SEARCHED_VAS_REPORTS';
export const ADD_NEW_VAS_REPORT = 'ADD_NEW_VAS_REPORT';
export const SET_VAS_REPORT_VALUE = 'SET_VAS_REPORT_VALUE';
export const UPDATE_VAS_CURRENT_REPORT = 'UPDATE_VAS_CURRENT_REPORT';

//=================== SAMPLE ===================
export const SAMPLE = 'SAMPLE';